/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mosq.glb --transform --simplify
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mosq-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.37, 0.14]} scale={0}>
        <mesh geometry={nodes.Object_14.geometry} material={materials.metal_black} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.MOSQCUER} position={[68.23, -115.96, 123.92]} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.MOSQCUER} position={[14.3, -86.63, 70.96]} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.MOSQOJOS} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.metal_black} position={[-0.29, -234.15, 155.86]} />
      </group>
      <group position={[-0.02, 0.35, 0.12]} scale={0}>
        <group position={[-194.27, 182.81, 177.92]}>
          <group position={[-64.78, -266.89, 293.47]}>
            <group position={[-33.16, -54.49, 77.13]}>
              <group position={[-16.6, -21.85, 39.46]}>
                <mesh geometry={nodes.Object_37.geometry} material={materials.MOSQPATA} />
                <mesh geometry={nodes.Object_39.geometry} material={materials.MOSQPATA} position={[-18.57, -14.93, 43.67]} />
              </group>
              <mesh geometry={nodes.Object_35.geometry} material={materials.MOSQPATA} />
            </group>
            <mesh geometry={nodes.Object_33.geometry} material={materials.MOSQPATA} />
          </group>
          <mesh geometry={nodes.Object_31.geometry} material={materials.MOSQPATA} />
        </group>
        <mesh geometry={nodes.Object_28.geometry} material={materials.MOSQPATA} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.white} />
      </group>
      <group position={[-0.04, 0.35, 0.08]} rotation={[0, 0, 1.13]} scale={0}>
        <group position={[-263.27, 182.81, -9.16]}>
          <group position={[-192.6, -224.83, 139.66]}>
            <group position={[-115.62, -84.15, 49.29]}>
              <group position={[-39.48, -24.76, 15.03]}>
                <mesh geometry={nodes.Object_50.geometry} material={materials.MOSQPATA} />
                <mesh geometry={nodes.Object_52.geometry} material={materials.MOSQPATA} position={[-40.57, -19.1, 16.98]} />
              </group>
              <mesh geometry={nodes.Object_48.geometry} material={materials.MOSQPATA} />
            </group>
            <mesh geometry={nodes.Object_46.geometry} material={materials.MOSQPATA} />
          </group>
          <mesh geometry={nodes.Object_44.geometry} material={materials.MOSQPATA} />
        </group>
        <mesh geometry={nodes.Object_41.geometry} material={materials.MOSQPATA} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.white} />
      </group>
      <group position={[-0.03, 0.36, 0.04]} rotation={[0, 0, 1.13]} scale={0}>
        <group position={[-111.5, 182.81, -238.67]}>
          <group position={[-211.94, -224.83, -108.09]}>
            <group position={[-96.45, -84.15, -80.59]}>
              <group position={[-31.33, -24.76, -28.34]}>
                <mesh geometry={nodes.Object_63.geometry} material={materials.MOSQPATA} />
                <mesh geometry={nodes.Object_65.geometry} material={materials.MOSQPATA} position={[-33.56, -19.1, -28.42]} />
              </group>
              <mesh geometry={nodes.Object_61.geometry} material={materials.MOSQPATA} />
            </group>
            <mesh geometry={nodes.Object_59.geometry} material={materials.MOSQPATA} />
          </group>
          <mesh geometry={nodes.Object_57.geometry} material={materials.MOSQPATA} />
        </group>
        <mesh geometry={nodes.Object_54.geometry} material={materials.MOSQPATA} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.white} />
      </group>
      <group position={[0.02, 0.35, 0.12]} scale={0}>
        <group position={[194.27, 182.81, 177.92]}>
          <group position={[64.78, -266.89, 293.47]}>
            <group position={[33.16, -54.49, 77.13]}>
              <group position={[16.6, -21.85, 39.46]}>
                <mesh geometry={nodes.Object_76.geometry} material={materials.MOSQPATA} />
                <mesh geometry={nodes.Object_78.geometry} material={materials.MOSQPATA} position={[18.57, -14.93, 43.67]} />
              </group>
              <mesh geometry={nodes.Object_74.geometry} material={materials.MOSQPATA} />
            </group>
            <mesh geometry={nodes.Object_72.geometry} material={materials.MOSQPATA} />
          </group>
          <mesh geometry={nodes.Object_70.geometry} material={materials.MOSQPATA} />
        </group>
        <mesh geometry={nodes.Object_67.geometry} material={materials.MOSQPATA} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.white} />
      </group>
      <group position={[0.03, 0.35, 0.08]} rotation={[0, 0, -1.13]} scale={0}>
        <group position={[263.27, 182.81, -9.16]}>
          <group position={[192.6, -224.83, 139.66]}>
            <group position={[115.62, -84.15, 49.29]}>
              <group position={[39.48, -24.76, 15.03]}>
                <mesh geometry={nodes.Object_89.geometry} material={materials.MOSQPATA} />
                <mesh geometry={nodes.Object_91.geometry} material={materials.MOSQPATA} position={[40.57, -19.1, 16.98]} />
              </group>
              <mesh geometry={nodes.Object_87.geometry} material={materials.MOSQPATA} />
            </group>
            <mesh geometry={nodes.Object_85.geometry} material={materials.MOSQPATA} />
          </group>
          <mesh geometry={nodes.Object_83.geometry} material={materials.MOSQPATA} />
        </group>
        <mesh geometry={nodes.Object_80.geometry} material={materials.MOSQPATA} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.white} />
      </group>
      <group position={[0.03, 0.36, 0.04]} rotation={[0, 0, -1.13]} scale={0}>
        <group position={[111.5, 182.81, -238.67]} rotation={[0, -0.09, 0]}>
          <group position={[211.94, -224.83, -108.09]}>
            <group position={[96.45, -84.15, -80.59]}>
              <group position={[31.33, -24.76, -28.34]}>
                <mesh geometry={nodes.Object_102.geometry} material={materials.MOSQPATA} />
                <mesh geometry={nodes.Object_104.geometry} material={materials.MOSQPATA} position={[33.56, -19.1, -28.42]} />
              </group>
              <mesh geometry={nodes.Object_100.geometry} material={materials.MOSQPATA} />
            </group>
            <mesh geometry={nodes.Object_98.geometry} material={materials.MOSQPATA} />
          </group>
          <mesh geometry={nodes.Object_96.geometry} material={materials.MOSQPATA} />
        </group>
        <mesh geometry={nodes.Object_93.geometry} material={materials.MOSQPATA} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.white} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.MOSQCUER} position={[0, 0.35, 0.06]} scale={0} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.MOSQCUER} position={[0, 0.35, 0.06]} scale={0} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.sayap_nyamuk} position={[0, 0.35, 0.06]} scale={0} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.sayap_nyamuk} position={[0, 0.35, 0.06]} scale={0} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.MOSQCUER} position={[0, 0.35, 0.06]} scale={0} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.MOSQCUL} position={[0, 0.37, 0.04]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.MOSQCUER} position={[0, 0.37, 0.03]} scale={0} />
    </group>
  )
}

useGLTF.preload('/mosq-transformed.glb')
