/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 logo.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/logo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[20.16, 33.66, 4.04]}>
          <mesh geometry={nodes.Shape_0.geometry} material={nodes.Shape_0.material} position={[-80, 60.25, -4.04]} />
          <mesh geometry={nodes.Triangle.geometry} material={nodes.Triangle.material} position={[1.08, 35.02, 3.04]} />
          <mesh geometry={nodes.Triangle_2.geometry} material={nodes.Triangle_2.material} position={[1.08, 16.66, 3.04]} rotation={[0, 0, -Math.PI]} />
        </group>
        <OrthographicCamera makeDefault={false} far={100000} near={0} position={[0, 0, 1000]} />
      </group>
    </group>
  )
}

useGLTF.preload('/logo-transformed.glb')
