// /*
//   Auto-generated by Spline
// */

// import useSpline from '@splinetool/r3f-spline'
// export function greenLogo({ ...props }) {
//   const { nodes, materials } = useSpline('https://prod.spline.design/u2Im0VkqBUTMVTp0/scene.splinecode')
//   return (
//     <>
//       <color attach="background" args={['#5e6063']} />
//       <group {...props} dispose={null}>
//         <mesh
//           name="Triangle 2"
//           geometry={nodes['Triangle 2'].geometry}
//           material={materials['Untitled Material']}
//           castShadow
//           receiveShadow
//           position={[103.08, -44.59, 7.07]}
//           rotation={[0, 0, -Math.PI]}
//         />
//         <mesh
//           name="Triangle"
//           geometry={nodes.Triangle.geometry}
//           material={materials['Untitled Material']}
//           castShadow
//           receiveShadow
//           position={[103.08, -26.23, 7.07]}
//         />
//         <group name="Group">
//           <mesh
//             name="Shape 0"
//             geometry={nodes['Shape 0'].geometry}
//             material={materials['Shape 0 Material']}
//             castShadow
//             receiveShadow
//             position={[22, -1, 0]}
//           />
//         </group>
//         <directionalLight
//           name="Directional Light"
//           castShadow
//           intensity={0.7}
//           shadow-mapSize-width={1024}
//           shadow-mapSize-height={1024}
//           shadow-camera-near={-10000}
//           shadow-camera-far={100000}
//           shadow-camera-left={-500}
//           shadow-camera-right={500}
//           shadow-camera-top={500}
//           shadow-camera-bottom={-500}
//           position={[200, 300, 300]}
//         />
//         <OrthographicCamera
//           name="1"
//           makeDefault={true}
//           zoom={5.72}
//           far={100000}
//           near={-100000}
//           position={[236.31, -67.08, 1069.53]}
//           rotation={[0, 0.12, 0]}
//           scale={1}
//         />
//         <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
//       </group>
//     </>
//   )
// }
