/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 termite.glb --transform --simplify
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Termite(props) {
  const { nodes, materials } = useGLTF('/termite-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.1, 0.01]} rotation={[0, 0.04, -Math.PI]} scale={0.22}>
        <mesh geometry={nodes.Object_10001.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_12001.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_14001.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_16001.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_18001.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_2.geometry} material={materials.Standard77352B} />
        <mesh geometry={nodes.Object_20001.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_22001.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_24001.geometry} material={materials.StandardF5A331} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Standard77352B} />
        <mesh geometry={nodes.Object_4001.geometry} material={materials.Standard77352B} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.StandardD87729} />
        <mesh geometry={nodes.Object_6001.geometry} material={materials.StandardD87729} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.StandardD87729} />
        <mesh geometry={nodes.Object_8001.geometry} material={materials.StandardD87729} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.StandardD87729} />
      </group>
    </group>
  )
}

useGLTF.preload('/termite-transformed.glb')
