/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 weed.glb --transform --simplify
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Weed(props) {
  const { nodes, materials } = useGLTF('/weed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Dandelion.geometry} material={materials['20___Default']} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
    </group>
  )
}

useGLTF.preload('/weed-transformed.glb')
